### ISSUE TITLE
Solve 327A - Flipping Game

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Codechef-practice-1#10]
Problem Link - https://codeforces.com/problemset/problem/327/A
Problem rating: 1200
Tag - brute force dp implementation
Platform - Codeforces
Difficulty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding

**Comment by Vivek2213** [comment]
Hey @Arpitgupta1014 , please let me to do this task.

**Comment by lancelot-zen** [comment]
@Arpitgupta1014, please assign me this task
