### ISSUE TITLE
Solve CHFNSWAP-codechef

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Codechef-practice-1#3]
Problem Link - https://www.codechef.com/SEPT20B/problems/CHFNSWAP
Tag -implementation
Platform - Codechef
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

 - Appropriate title for PR
 - Making another file with an appropriate name.
 - Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by hrs-2703** [comment]
sir i want to solve this issue
