### ISSUE TITLE
Solve HEADBOB-Codechef

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Codechef-practice-1#4]
Problem Link - https://www.codechef.com/problems/HEADBOB
Tag - implementation
Platform - Codechef
Difficulty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

 - Appropriate title for PR
 - Making another file with an appropriate name.
 - Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by amansingh854** [comment]
Hey @Arpitgupta1014, Can I work on this issue?

**Comment by Arpitgupta1014** [comment]
Nice work @amansingh854
