### ISSUE TITLE
Solve WATSCORE-Codechef

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Codechef-practice-1#5]
Problem Link - https://www.codechef.com/problems/WATSCORE
Tag - implementation
Platform - Codechef
Difficulty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by Vivek2213** [comment]
hey @Arpitgupta1014 , please let me do this task . i have solved various poblem like this . so i think i am able to do this.

**Comment by ShivanshDengla** [comment]
Hey can i solve this problem?
