### ISSUE TITLE
Solve Greater Average Codechef in JAVA

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Codechef-practice-1#6]
Problem Link - https://www.codechef.com/START53D/problems/AVGPROBLEM/
Tag - implementation
Platform - Codechef
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

An appropriate title for PR
Making another file with an appropriate name.
Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by ShivanshDengla** [comment]
Hey can i work on this problem?
Thanks

**Comment by hrs-2703** [comment]
sir  can i work on this problem

**Comment by ShivanshDengla** [comment]
Excuse me sir,
Did you delete my comment or was it a glitch?

**Comment by JayantVashishtha** [comment]
Sir I would like to contribute in this task.

**Comment by Arpitgupta1014** [comment]
Good work @Hrs-pandit
